accounts/urls.py
# accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [    
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
]

blogPosts/urls.py
# blogPosts/urls.py
from django.urls import path
from blogPosts import views


app_name = 'blogPosts'
urlpatterns = [
    path('', views.index, name='index'), # 'localhost:8000/posts/'
    path('new/', views.new, name='new'),
    path('<int:id>/', views.show, name='show'),
    path('<int:id>/delete', views.delete, name='delete'),
]

seminar/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

import blogPosts.views
import accounts.views

# connects requested url with the function in blogPosts/views.py
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blogPosts.views.index, name='index'),
    path('posts/', include('blogPosts.urls')),
    # path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', accounts.views.signup, name='signup'),    
]

accounts/models.py
# accounts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User   # 추가

from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):   # 추가    
    user = models.OneToOneField(User, on_delete=models.CASCADE) # User와 연결
    college = models.CharField(max_length=20, blank=True) #college field 추가
    major = models.CharField(max_length=20, blank=True) #major field 추가
    def __str__(self):   # 추가        
        return f'id={self.id}, user_id={self.user.id}, college={self.college}, major={self.major}'
    # 아래 코드 추가  
    @receiver(post_save, sender=User)  
    def create_user_profile(sender, instance, created, **kwargs):        
        if created:          
            Profile.objects.create(user=instance)  
    
    @receiver(post_save, sender=User)  
    def save_user_profile(sender, instance, **kwargs):        
        instance.profile.save()

blogPosts/models.py
# blogPosts/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model): # 모델 클래스명은 단수형을 사용 (Posts(x) Post(O))
    # id는 자동 추가
    title = models.CharField(max_length=256)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(blank=True, null=True)

    def update_date(self): # 나중에 수정할 때 사용
        self.updated_at = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'[post: {self.post}] {self.content}'

accounts/views.py
# accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User  # 추가
from django.contrib import auth  # 추가
from django.shortcuts import redirect  # 추가

def signup(request):
    # 추가
    if request.method  == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
            auth.login(request, user) #로그인 시켜주는 기능
            return redirect('/posts')

    return render(request, 'accounts/signup.html')

# def login(request):
#     if request.method == 'POST':
#         user = auth.authenticate(username=request.POST['username'], password=request.POST['password1'])
#         auth.login(request, user)
#         return redirect('blogPosts:index')
#     return render(request, 'accounts/login.html')

blogPosts/views.py
# blogPosts/views.py
from django.shortcuts import render, redirect # redirect 추가
from .models import Post
...
# index 함수 코드 변경
def index(request):
    if request.method == 'GET': # index
        posts = Post.objects.all()
        return render(request, 'blogPosts/index.html', {'posts': posts})
    elif request.method == 'POST': # create(form을 이용하여 submit한 형태) 
        title = request.POST['title']
        content = request.POST['content']
        Post.objects.create(title=title, content=content)
        return redirect('blogPosts:index')
...

def new(request):
    return render(request, 'blogPosts/new.html')

def show(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'blogPosts/show.html', {'post':post})

def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect('blogPosts:index')

accounts/templates/accounts/signup.html
<!-- accounts/templates/accounts/signup.html -->
<h1> Sign Up! </h1>
<form method="POST" action="{%url 'signup' %}">
    {% csrf_token %}
    User name:
    <br>
    <input name="username" type="text" value="">
    <br>
    <br>
    Password:
    <br>
    <input name="password1" type="password" value="">
    <br>
    <br>
    Password Confirmation:
    <br>
    <input name="password2" type="password" value="">
    <br>
    <br>
    <input type="submit" value="Sign Up!">
</form>

blogPosts/templates/base.html
{% comment %} blogPosts/templates/base.html {% endcomment %}

<!DOCTYPE html>
<html>
	  <head>
    <meta charset="utf-8">
    <title>snulion</title>
		{% comment %} 아래 세 줄을 추가해 scss 파일을 import 해줍니다 {% endcomment %}
		{% load static %}
		{% load sass_tags %}
		<link rel="stylesheet" type="text/css" href="{% sass_src 'blogPosts/scss/style.scss' %}">
  </head>
  <header>
    <div style="text-align: right;">
        {% if user.is_authenticated %} 
             {{ user.get_username }}, hello! 
             <a href="{% url 'logout'%}">Log out</a>
        {% else %} 
             <a href="{% url 'signup' %}">Sign up</a> 
             <a href="{% url 'login' %}">Log in</a> 
        {% endif %} 
    </div>   
    Snulion Blog
  </header> {% comment %} header를 작성해줍니다 {% endcomment %}
  <body>
  {% block content %}
  {% endblock %}
  </body>
</html>

blogPosts/templates/blogPosts/index.html
<!-- index.html -->
{% extends 'base.html' %}

{% block content %}
    <h1>POSTS</h1>
    <a href="{% url 'blogPosts:new' %}">new post</a>
    {% for post in posts %} 
      <div style="border: 1px solid grey;">
				<a href="/posts/{{ post.id }}/"> 
{% comment %} <a href="{% url 'blogPosts:show' post.id %}">  {% endcomment %}
          <h3>{{ post.title }}</h3>
        </a>
      </div>
    {% endfor %} 
  {% endblock content %}

blogPosts/templates/blogPosts/new.html
{% extends 'base.html' %}

{% block content %}
    <h1>new post</h1>
    <form action="{% url 'blogPosts:index' %}" method="POST">
{% comment %} 위의 경로는 action="/posts/"과 같습니다 {% endcomment %}
      {% csrf_token %}
      <p>title</p>
      <input name="title" /> <br />
      <p>content</p>
      <textarea name="content" rows="30" cols="50"></textarea> <br />
      <input type="submit" value="submit" />
    </form>
{% endblock content %}

blogPosts/templates/blogPosts/show.html
{% extends 'base.html' %}

{% block content %}
    <div>
      <a href="{% url 'blogPosts:index' %}">home</a>
      <h1>{{ post.title }}</h1>
      <p style="width: 70%;">{{ post.content }}</p>
      <a href="{% url 'blogPosts:delete' id=post.id %}">Delete</a> <!-- add -->
          <!-- 여기서부터 새로 추가한 코드 -->
              <p><strong>There are n comments </strong><p>
          {% for comment in post.comment_set.all %}
            <p>
              {{ comment.content }}
            </p>
          {% endfor %}
          <!-- 새 코드 끝 -->
    </div>
{% endblock content %}